sudo: false
language: node_js
node_js:
- 12.16
script:
- npm install
- npm test
- npm run build
deploy:
- provider: releases
  api_key:
    secure: T15FMNuLJuvyEUFOaC1VmxFyu2iNkpjA1tU0vXtCSryyA2YXvXudg+EFtCKHVKN7Dz+yWPytUS/OAGiMrI37H2uSp3kRPwlFVC+qRrqRXbYTfLRLcgXSnrMldsq3u9n9OvRmqak0fa5gkbnk/i3ACPbqZaR995XxulDooX7k4w3lyXYlz+ZesVeUnDlWVXOMBheXy754pCPfdPhbgPriohqAPgPKMBVDC80ss1cAmBw/cwt8ZxM9S8vYjOK7xNKy1lRB2BCdgUggms5eIWqe3UrkVZjtmnHYqPYYM9ooK+CK74w5sHpAfHTYRurDCgnOViJlEOnaFe6TP/DcJSrMcS76C/20WFk/ws2ov7Hh6yDFBy31jix1esX9Mruf8mTRAiYTCNjM/d+PE+LqknSuVmrLZi3EOLBepkFJ/9EUx0QNT4vN7c8AlyQPZQx7mAp2+UBBsSmUT9cdkw9/+zNqypnQKJkEJ5vmM/2jkAHXieImvfelsWB+On7pd4PN9v0EqlN1NCEy9A6B1ceNo1QHpYn/VGpkFmKy+CKFf6wj9KV1xO3zm1Z4YD7nEYdHn+73I8QDCnznE1r1qyKc5cY3C57oJUVrmH0by4hI69DjGpUyr4vrQIno+LFRiwFFqt59/5zr83fMt5gkwS0kEJ3/89XF5lVkcTvw0uQdRy0F2Nk=
  file: dist/headbreaker.js
  on:
    repo: flbulgarelli/headbreaker
    tags: true
  skip_cleanup: true
- provider: npm
  email: franco@mumuki.org
  api_key:
    secure: Su8HOM+CYoNo+aJFtMXpgRkT1yIeNX8mxtFLxyqZOP8LQuOLfafKzkNJXgq6vUggo4YEhq+WCC4d6RQbFEbYucBcL33+5Qq/+Avp3OOequekKLvxBhtDDNUDMXP3v+F5XZzISBp65B58e3pq4UNY15/xA+hqp7PVkcDZpM+T1Vw+ImGx9EwjPxbJ7FWpxB4QOGHPZKoEGu0keDJPeVDEwszP1t5A4+2MYb0UCxyeyeWa0IfWKpS1nK8I8YBCutOuAA2i5JccvKm79pjD5dR9NHZxpKl+TPkJRAfVWngzNKxw7F6GaV7+kH7d+D1xg80d4b8d6pwDvy/KByxCIdD87xCJeLr5l7AIIPHiPtUVm4kcMUB4q/DN530LSI4rmpGau6wGpmODAMB+NEN/nHSGEplzi/sLUsNgob4YkN4FL0/3aDmZSS8kPqCNwC/Xoao1UdDzWhnWGOYfZ4+fQqQTHa0YSAbTKaFdICW4s+Mhvqjm/WMpFnVIIKJsNqBuqgA6s7p8PPc6icHiWy701rmdePyO0VZvJJ4+lVqL9K7GJqrj9eLcFezDiXFs7IYB2TkQyH015Te2wqIY9Ezm6wHD9SeHRTJapHR+VrtFeR7jAgz8dxoTgKpciV4exMAlbuyvYfzhkt8+Y3ftI5nsEItXW782UwGAj8XweIGfPFv7krI=
  on:
    repo: flbulgarelli/headbreaker
    tags: true
  skip_cleanup: true
